stages:
  - lint
  - test

default:
  tags:
    - docker-runner

pylint:
  image: python:3.12-alpine
  stage: lint
  script:
    - cd service2
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install pylint==3.3.3
    - pylint *.py

eslint:
  image: node:21-alpine
  stage: lint
  script:
    - npm install @eslint/js@9.17.0 eslint@9.17.0 globals@15.14.0 typescript-eslint@8.18.2
    - npx eslint

browser-endpoint-test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker-runner
  script:
    - docker-compose -f docker-compose.yml up -d --build
    - export TEST_COMMAND="npm run test:browser" && docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from test-container
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose-test.yml down

state-api-test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker-runner
  script:
    - docker-compose -f docker-compose.yml up -d --build
    - export TEST_COMMAND="npm run test:state-api" && docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from test-container
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose-test.yml down

