image: node:21

stages:
  - test

test:
  stage: test
  tags:
    - docker-runner
  script:
    # Install Node.js dependencies for service1
    - cd service1
    - npm install
    # Run Jest tests for service1
    - npm test
