name: compse140-project
services:
  service1:
    build: ./service1
    depends_on:
      - service2
    deploy:
      replicas: 3
    environment:
      - PORT=8081
      - SERVICE2_URL=http://service2:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  service2:
    build: ./service2
    networks:
      - app-network

  nginx:
    build: ./nginx
    depends_on:
      - service1
    networks:
      - app-network
  gateway:
    build: ./gateway
    ports:
      - "8198:8198"
      - "8197:8197"
      - "8098:8098"
    environment:
      - NGINX_URL=http://nginx:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
