# This file overrides the docker-compose.yml file service properties to use the images built in the build stage. The file can be used with the docker-compose.yml file to deploy the application to a production environment.

services:
  service1:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/service1:${CI_COMMIT_SHA}
    build: !reset null
    restart: always

  service2:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/service2:${CI_COMMIT_SHA}
    build: !reset null
    restart: always

  nginx:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/nginx:${CI_COMMIT_SHA}
    build: !reset null
    restart: always

  gateway:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/gateway:${CI_COMMIT_SHA}
    build: !reset null
    restart: always
