services:
  test-container:
    build: ./test
    networks:
      - test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  test-network:
    external: true
    driver: bridge
