services:
  service1:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/service1:latest
    build: !reset null
    restart: always

  service2:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/service2:latest
    build: !reset null
    restart: always

  nginx:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/nginx:latest
    build: !reset null
    restart: always

  gateway:
    image: compse140.devops-gitlab.rd.tuni.fi:5050/ckmali/comp.se.140-project/gateway:latest
    build: !reset null
    restart: always
