services:
  service1:
    build: ./service1
    depends_on:
      - service2
    deploy:
      replicas: 3
    environment:
      - PORT=8081
      - SERVICE2_URL=http://service2:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service2:
    build: ./service2

  nginx:
    build: ./nginx
    ports:
      - "8198:8198"
    depends_on:
      - service1
